### ISSUE TITLE
Make inlineSchema not json encoded

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#111]
It seems weird to me to be json encoding data inside json. Why not just have it as an object?

**Comment by fugu13** [comment]
This basically isn't an option. json-schema have arbitrary keys (since the keys of the format being described are used as keys in the json-schema document), so in order for it to fit in as well-structured JSON-LD anyone using it would need to put a different context every time, with the keys they were using, which is a lot of error prone work for basically zero benefit other than not needing to serialize the json-schema to a string (which is easy and not error prone).
