### ISSUE TITLE
Statement Templates Rules selector

### ISSUE THREAD

**Issue by cr8onski** [adlnet/xapi-profiles#119]
I do not understand how this is to be used?  My best guess is that if location were context.contextActivities.grouping, then selector would be 0, or [0].  Does that come close?

**Comment by fugu13** [comment]
This is to handle a particular sort of situation involving multiple matching values. Imagine I have the following rule:
```javascript
{
    "location": "$.actor.member[*].account",
    "rule": "included"
}
```

Looks good, we're requiring every member of the actor Group have an account. Except what happens with this as the actor?

```javascript
{
    "objectType": "Group",
    "member": [
        {"account": {"homePage": "http://example.com", "name": "orange"}},
        {"mbox":"mailto:orange@example.com"}
    ]
}
```

There's a value found by the JSONPath, so included is satisfied, but not every member has an account.

Using selector solves that. We update the rule to:

```javascript
{
    "location": "$.actor.member[*]",
    "selector": "$.account",
    "rule": "included"
}
```

First, we find all member values. Then, for each member value, we apply the selector, and if the selector does not match, an unmatchable value is produced. Since one of the members does not have an account, it produces an unmatchable value, which rejects included per the required logic.
