### ISSUE TITLE
a template with a set of ok verbs

### ISSUE THREAD

**Issue by creighton** [adlnet/xapi-profiles#121]
For SCORM objectives there are a few verbs that could be acceptable in a template, such as passed, failed, completed, scored. Is there a way to make a single template that has the activity type of "..adlnet/...objective" and a verb list of those verbs?

My initial thought was...
```
{
            "@id": "_:objectiveactivity",
            "name": {
                "en": "objective activity"
            },
            "verb": [
                "http://adlnet.gov/expapi/verbs/passed",
                "http://adlnet.gov/expapi/verb/failed", etc..
            ],
            "objectActivityType": "http://adlnet.gov/expapi/activities/objective",
            "contextParentActivityType": "http://adlnet.gov/expapi/activities/lesson",
            "rules": [
            ]
 }
```  

My second thought was...
```
{
            "@id": "_:objectiveactivity",
            "name": {
                "en": "objective activity"
            },
            "verb": { "alternates": [
                "http://adlnet.gov/expapi/verbs/passed",
                "http://adlnet.gov/expapi/verb/failed", etc..
            ]},
            "objectActivityType": "http://adlnet.gov/expapi/activities/objective",
            "contextParentActivityType": "http://adlnet.gov/expapi/activities/lesson",
            "rules": [
            ]
 }
```  

Or I could create a new template for each one with the verb being the only difference?

Any guidance on how to approach this would be appreciated

**Comment by fugu13** [comment]
Currently the way to do this is to list each statement template separately, and while there are occasional awkwardnesses, I'd prefer to keep it that way for a few reasons.

1. even if the statements are structurally identical except for the verbs, they should probably have different names and descriptions focused on the use of the particular statement.

2. it will promote a subtle class of errors, with people accidentally putting statements together because of structural similarity then using the single statement template in a pattern where, say, one of the statements isn't actually allowed.

3. the use of every other array-valued determining value in statement templates is that *all* must be present, so making verb array-valued and allowing *any* to be present would be a notable departure.
