### ISSUE TITLE
Concept Typing Limitations

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#124]
Concepts are limited by a requirement to a type of Verb, ActivityType, AttachmentUsageType, ContextExtension, ResultExtension, ActivityExtension, StateResource, AgentProfileResource, ActivityProfileResource, or Activity.  

The cmi5 profile makes use of a ContextActivity with a type of "category" to tag Statements of that type.  Other profiles have this behavior as well, but cmi5 is the first to define two for the same spec and thus creating separate identifiers for each category.  This use case makes me wonder about either a) allowing in any type, knowing that only limited guidance will be available, b) expanding Activity so that the "tagging" function of context Activities could be more effectively used or c) introducing either ContextActivities or categories as another type.

**Comment by fugu13** [comment]
The cmi5 Activity representing the profile that goes in the category section of context activities does not have any type (see: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#9621-cmi5-category-activity ).

The other Activity that goes in context in cmi5 is basically a retrieval filter (it just marks cmi-defined statements that have success or completion set) for certain subsets of cmi5 activity. It has nothing to do with the "type" of anything, just with making it easier to filter for particular sorts of statements in the limited filtering allowed by xAPI.

And I don't understand what you mean by any of "allowing in any type", "expanding Activity so that the "tagging" function of context Activities could be more effectively used", or "introducing either ContextActivities or categories as another type."

Activity is already a concept. Activities are what go in context activities sections, including in category. The Activities given can be defined with any activity type.

**Comment by andyjohnson** [comment]
You had me at we can use the Activities in Category.  I thought it was restricted and was pushing for expansion in option "c" above.  The separation of extensions into their locations and not the separation of Activities in a similar way aided this assumption.  May be worth just throwing in a bit of explanatory text in the Activities section in Concepts.
