### ISSUE TITLE
Reword "The serialized JSON form of an xAPI Profiles 1.0 profile version"

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#134]
This is quite a mouthful. Can we break it up at all? Maybe something like...

> Profile versions can be serialized as JSON as defined in this specification, xAPI Profiles 1.0. When in this format, the profile version must be consistent...

But maybe we can simplify it more:
* Do we need to specify the name and version of the spec here? Perhaps this can be listed elsewhere. 
* Can we use the term "profile" instead of profile version? It seems like it will get annoying to refer to profile versions throughout. Can we agree that the term "profile" normally refers to a specific version?
* Is there such a thing within this spec as a profile that is not serialized as JSON? If not, "The serialized JSON form" is redundant. 

In which case, we can reduce "The serialized JSON form of an xAPI Profiles 1.0 profile version" to "Profiles".

**Comment by fugu13** [comment]
I think we can drop the spec part and do a bit of rewording. I think it should probably be profile version to be precise--this is intended to be one of finicky ultra-precise bits because there's a lot of potential for misunderstanding.

And yup, profiles can exist in a form other than JSON -- they can just be the constituent RDF of the JSON, which is how most people will end up interacting with them (via SPARQL).

**Comment by fugu13** [comment]
Hmm, had an idea that might make it okay to leave off "version"

**Comment by fugu13** [comment]
Idea: split at "using" into second sentence.
