### ISSUE TITLE
Goals of the profile spec

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#20]
It would be good to include a summary of the purpose and goals of the spec. My goals in contributing are encapsulated in these questions which I'm using to review the document:

1. Would profiles defined following this spec contain enough information for a Learning Analytics Platform
(specifically Watershed) to automatically and without human intervention generate useful reports from the data?
2. Related to item 1, would profiles defined using this spec be prescriptive enough to ensure LRPs implementing the profile are consistent enough in their statements to facilitate item 1?
3. Are the profiles easy to create? The biggest problem with profiles today is the lack of anybody publishing them. The spec should make it easier to create profiles, not harder.

**Comment by fugu13** [comment]
I know these are for your consideration, but roughly going through them to add some discussion:

Starting with 2, this one's easy -- yes. The fuzziest parts needing fiddling with will be around extensions and document resources, but even those are pretty solid.

Moving on to 1, because why not, to a certain extent this is a perspective dependent question -- it will never be possible for a profile spec to make it possible to generate *all* interesting reports (or even all that many) without human intervention. But I'm confident there are several, perhaps even many, interesting reports that can be generated without human intervention for each profile, and I'm happy to describe some of them and how they could be accomplished. The main remaining difficulty is deciding if there are any reports that *should* be possible to generate human intervention that the current profile spec does not make possible, and I can't really take a stab at that without a candidate "missing report".

Lastly, 3. Profiles should be much easier to create by hand than vocabulary spec documents, due to increased strictness, removing certain options that led to confusion for little gain, and better alignment with already-available tooling (the JSON-LD compaction operation, which there are nice web forms and libraries for). It is a fuzzier question, but I believe they should also be easier to create than "by hand" human-readable-only profiles, which have suffered from scattered conceptualization of what a profile is and lack of clarity about what should be included; certainly they will be much easier to use once created, and I think a big barrier has long been lack of clear ways to put profiles to work.

Also, even during the "by hand" period, I think people authoring complex profiles will be boosted by having a clear spec to target and a defined community of people more expert in profile authoring to ask technical questions of.

Beyond writing by hand, it should be possible to create incrementally improving tooling that helps author profiles -- for example, an early approach could be authoring verb/activity type/etc relations via one of the several SKOS authoring tools, exporting, and uploading with a form that takes a little basic metadata and spits out a profile. From there, we could eventually reach very sophisticated authoring GUIs over a series of increasingly complex tools.

One thing I hope to see, and intend to contribute to, is several "mini-profiles" that have good building blocks for common cross-cutting use cases -- metrics collection, for example. These should be possible to use alongside with, even in the same statements as, "larger" profiles. They should also serve as examples of how to construct profiles, which can only help make authoring more approachable.

Whew! Longer than I thought it would be when I first started writing, but I hope that's helpful.
