### ISSUE TITLE
Profile and version URIs MUST be included in statements following that profile

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#22]
This allows the LRC to identify that the statement follows that profile. 

See for example https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#context_activities_category_cmi5

**Comment by fugu13** [comment]
Yes, this is included (well, I'm not sure where it'll come down on main profile URI, version URI, or both, but there's some complexity behind that). Right now that's expressed as a SHOULD, mostly because statements could accidentally conform and it would be weird to penalize them for not including the profile in the category, but that's followed by a MUST that statements using the profile in category have to conform.

https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#using-profiles-in-statements

The line that's being split in the paragraph linked is between using concepts introduced by the profile and following the stricter rules in the profile. For example, the ADL will publish a profile with lots of verbs in it but probably not a single stricter rules; we probably don't want to say that every statement using those verbs has to include the ADL's profile identifier, because that'd be weirdly incompatible with current practice.

But if the ADL formalized their SCORM profile with rules on statement templates and ordering, I think it'd be reasonable to expect systems following that profile that wanted the benefits of profile conformance to include the profile in category -- while at the same time, there'd be a bunch of systems accidentally following it who we can't really require to add the profile to category as a practical matter (though they should probably start looking at it).

**Comment by garemoko** [comment]
Thanks for pointing that out. I missed that bit. 

I think we agree on the approach, although I conceptualise it differently. I agree that implementing parts of a profile is all good, but in that case I'd say they aren't following the profile and therefore aren't covered by any of the requirements of that profile or of the profile spec. I'll take an action to have a go at re-wording the 'Using Profiles in Statements' section as I think it'll be clearer if I propose some actual text for us to debate. 

Other points for discussion on a call:
* should we MUST require the inclusion of both version and profile ids in statements. I say yes, because otherwise why bother having them? 
* should people partially implementing a profile include the ids? I see pros and cons to this. If they include the id, there's potential for the LRC to assume they implemented the profile completely and then get confused by their statements. If they don't include the id but their implementation is close enough to the profile to actually work for what the LRC is doing, then it's a missed opportunity. I think my vote is on not including the id and encourage profile creators to mark elements that might be more difficult to implement as optional.

**Comment by fugu13** [comment]
The versions serve a useful purpose management side even if they aren't included in statements, but I can see a case for including them in statements too. We should game out some scenarios for the different approaches to see if there's much benefit to including them in statements, and if there is if there's any additional benefit to including the parent profile ID in statements (I'm increasingly thinking we might want *only* the version).

Re: partially implementing, my rough thought is if all statements an LRP is sending with a particular profile identifier will be found to match statement templates and obey patterns (if any exist), it should be okay to do so, even if there are templates and patterns the LRP doesn't use.

Profiles that want to be much stricter, such as CMI5, would be free to include text about not doing so unless the other rules are followed, but as I think we're seeing with video and a number of other profiles, there are lots of profiles that won't even have the concept of being implemented "completely" much less an ability to enforce it.

**Comment by garemoko** [comment]
The reason we need both version and id in the statement is that an LRC might have functionality that works with any version, or might have functionality that works only with specific versions. I guess they could list all the versions, but it would be nice not to. 

They don't need to be two context extensions though. The profile id could be an activity definition extension of the version activity. That'd be a little more compact in the statement and easier to work with I think.

**Comment by garemoko** [comment]
"would be free to include text about not doing so " - I'd prefer to be able to read this automatically if possible. Patterns in which all statement templates are optional (for very flexible profiles) or all are required (for very strict profiles) could solve this. 

(Apologies if I'm misrepresenting patterns. I didn't read that bit yet)

**Comment by fugu13** [comment]
> an LRC might have functionality that works with any version

I don't think they can ever know that, since there may be future versions. And any tool that's validating the profile will definitely want to "follow" the version, which'll lead to the main profile ID already, which is why I don't think both are needed. So long as the LRC links to _one_ version that works, things should be fine. There's a little trickiness around defining how that interacts with patterns, I think, but not so much as all that.

I think it should go in category context activities and stay out of extensions; this sort of use is what they're for.

**Comment by fugu13** [comment]
Yes, patterns allow for both optionality and all required and lots of variations and combinations, so I think there might already be enough of what you're looking for.

**Comment by garemoko** [comment]
re https://github.com/DataInteroperability/xapi-profiles/issues/22#issuecomment-291964988

Good point. And I guess for all practical purposes most profiles aren't going to have that many versions to make listing them unduly onerous.

**Comment by fugu13** [comment]
Yeah, I'd expect even well-loved profiles to have one first version, another a few months or a year later tidying things up and adding missing things, and then not much for a long while.
