### ISSUE TITLE
Is altLabel necessary?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#27]
I'm not clear on the purpose of altLabel I get that it's an alternative, non-preferred label, but is restrictive or suggestive? I.e. am I allowed to use a verb display that is not either the preferred or alternate label for that verb?

If it's suggestive, then why have it? We have the label that we want people to use, why suggest another one?

I don't see any reason for it to be restrictive - why limit people from using any alternative label? 

In any case, if we keep it then it should be a language map of arrays (a list of values per language). There's no reason why there should be exactly 1 alternative.

**Comment by fugu13** [comment]
altLabel is there partly to provide guidance on particular alternatives that might be in use--"here's a verb, here's how you should probably display it, but be aware some people are sending data with this other display". It is also partly for discovery -- someone might type a search term in while looking for something, and if it exactly/closely matches an altLabel that verb could be surfaced.

I do think the value is minimal overall; I nearly dropped altLabel along with some other things from the vocabulary spec.

Re: array, yep, I'd already made a note to change that but it looks like I hadn't added it to the issues yet (there's a way to have language tagged values in an array instead of a map in JSON-LD, which is what we'd use). If we keep altLabels that'll happen

**Comment by fugu13** [comment]
I'd like to get rid of altLabel, thinking about it.

**Comment by fugu13** [comment]
Consensus reached, remove it
