### ISSUE TITLE
Extension placement issues

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#30]
First up, the extensions placement property seems to be doing two separate things:

1. Determining where in the statement the extension can be used. 
2. Determining which activity types an extension is valid to be used with.

These should be split out into separate properties (if we keep both parts). 

Second, it seems odd to be restricting statements to certain activity types like this. Why not use Statement Templates instead? 

Third, do we really want this to be an array? Surely extensions should always be used in the same place? If it is an array (maybe to support using a profile to document real life usage), should we strongly recommend the array only has 1 value?

**Comment by garemoko** [comment]
Regarding the point about this being an array vs a single value, see the Document Resources @type property. I feel we should be consistent between the two.

**Comment by fugu13** [comment]
Here's an example for why placement was chosen to be an array. Imagine a general location extension that, when used in context represents the place the statement occurred, and when used in result represents a location that was the conclusion of the experience in some sense (such as the town someone ended up in in a military simulation move), and when used in activity is the location the activity is based in (perhaps the activity actually represents a location itself). That could all be nicely defined in one thing with one extension key and multiple placements.

This is versus type, where I have a hard time coming up with a good example of why there'd be anything structured identically in multiple of State, Activity Profile, and Agent Profile. I can see some contrived ones, but they all feel really fake so far. I'm definitely open to hearing an example going the other way though.

**Comment by fugu13** [comment]
I can see the argument for moving restrictions to particular activity types to statement templates; the main thing that gives up is it no longer becomes possible to allow it to be open to any narrower form. What I was sort of imagining as a use case here is, someone defines a profile with a general activity type (say, audiovisual material), and says, here are some extensions based on it. Then anyone could use those extensions on the general audiovisual type, or on narrower than audiovisual activity types defined by other profiles.

Or we might just say that extensions shouldn't generally be restricted by activity type; that's currently basically the practice, but it also seems to make a lot of sense that many extensions go with particular activity types (albeit general ones... that are then nicely available for people to make more specific ones of!)

I put them in the same array because it is parallel to the other sorts of placement; you can put them in the result, or the context, or an activity of a particular type... you get the idea. I'm not committed to that representation, though.

**Comment by garemoko** [comment]
re https://github.com/DataInteroperability/xapi-profiles/issues/30#issuecomment-291957594
I'd really rather have three different extensions in that example because they mean different things. I can see the niceness of re-usability but I think the risk of people putting the extension in the wrong place is too high. 

On the other hand, perhaps we can mitigate that risk by being strict on extension placement in the statement templates. I haven't reviewed the statement template section yet. 

One use case for the same document being used in multiple places is bookmarking data used for an activity that can be single or multi "player". The single player data would be stored in the state, the multiplayer data would be in the activity profile.

**Comment by garemoko** [comment]
re https://github.com/DataInteroperability/xapi-profiles/issues/30#issuecomment-291959295
I can see the argument for restricting activity definition extensions to particular types for sure. My point is that statement templates, or possibly partial statement templates would be a better place to do it. There's also arguments for particular context or especially result extensions to be tied to particular verbs in the same way and I don't see why activity types should be this special thing. 

Could statement templates be used to support the use case you described?

**Comment by fugu13** [comment]
Statement templates could restrict an extension to being in activities with a particular activity type or list of activity types, for statements sent with the profile in the context (which wouldn't restrict the use of the extension in activities in statements without the profile in the context).. I think that might end up being okay. That'll tend to lead to a certain amount of duplication, as then other profiles with narrower forms of the activity might want to include what are essentially the same restrictions...

Actually, I've just thought of why it makes sense to include the activity types, and include them in extensions: authoring hints. There are going to be a bajillion extensions, and a natural flow for someone wanting to create the data for a new activity will be to 1) choose an activity type and 2) see what extensions make sense to use with that activity type. So this isn't so much about restricting (and should probably be explicitly made not restrictive, which is a reason to move it out of the placement list, like you suggested before, since the placement list should be restrictive) as it is about guiding. And that's a much larger question than "what extensions are explicitly mentioned in a template", especially as it would be very very nice for one profile to be able to offer extensions to be used on another profile's activity types.

**Comment by garemoko** [comment]
Maybe, but doesn't that also apply to result/context extensions that only make sense with a specific verb? Do activity types and definition extensions need to be special?

**Comment by fugu13** [comment]
Good point, those should probably be added as well.

**Comment by fugu13** [comment]
This is one of the big open issues, exactly how this will work. I'm working through some of the details but haven't got a PR ready yet.
