### ISSUE TITLE
non binary rules for statement templates

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#36]
I wonder if it's worth adding the following to the potential values of statement:

- recommended - the LRP is recommended to use this statement property but the LRC cannot expect it to be always included. 
- optional - the LRC might want to look out for this property and use it if included, but there's no expectation on the LRP to provide it.

**Comment by fugu13** [comment]
Hmm, not sure. I'd love to see some more specific examples to help flesh out the amount this would actually help.

**Comment by garemoko** [comment]
The [video recipe](https://registry.tincanapi.com/#profile/19) says "Video Activity Definition includes the following: ... If available include the length of the video in 'extensions' using: http://id.tincanapi.com/extension/duration" That would be a recommended property. 

The [Open badges recipe](https://registry.tincanapi.com/#profile/44) also has recommended properties. 

I have less concrete examples for the 'optional' tag, but you could imagine a type of activity that is sometimes scored and sometimes not scored including score as an optional property in statements.

**Comment by fugu13** [comment]
Re: optional, all properties are sort of optional by default unless included or excluded

I think most of the roles of recommendation (which will always mostly be about extensions, since ppl writing templates already are fully informed about the non-extension structure of statements) are well-filled by putting activity types and verbs and such in the extension definition, which'll have the benefit of being "recommendation-y" for other uses of those entities.

For your video example, the video activity type would listed for the duration extension. And for open badges, all the extensions would list the open badge activity type.

The video example does illustrate a need to comment on concepts defined in other profiles, though, which has usually been left out. I'll play around with some syntax for that.

**Comment by garemoko** [comment]
My understanding of what you're suggesting is that we'd list the statements the extensions are intended to be used in within the human readable definition property of extensions. Did I understand that right?

There's two problems with that:
1. It's not machine readable so the LRC has no way of automatically determining it should be looking for these extensions. 
2. What if the profile author wants to include an extension in a statement that's not defined in that profile? 

Is there any specific downside to including optional and recommended flags in statement templates? 

Regarding optional, yes all properties are optional, but including optional properties in a template tells the LRC to specifically look for those properties because while they won't always be present, they's a good chance of them being there some of the time.
