### ISSUE TITLE
In pattern sequence, does "in the order specified" relate to stored or timestamp?

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#41]
I think it should relate to timestamp but that could be difficult to validate as at any point in time there could potentially be more statements on their way that would satisfy the pattern.

**Comment by fugu13** [comment]
This would probably be two-fold: on initial intake things would be validated in the order received (while eventual consistency makes total order pretty difficult, there are reasonable practical approaches to handling a practical message receipt scenario where small subsets need to be ordered but total order doesn't matter much), provided timestamp aligns.

For reprocessing/reintake, order would be based on timestamp, and most validation would be post-hoc, presumably, rather than as statements arrive. How an LRS chooses to apply that would be to a certain extent left up in the air (after all, choosing to do any sort of profile validation at all will be to a certain extent flexible).

I see a few possible ways to distinguish initial intake and reprocessing/reintake. One would be to send an http profile header with statements being sent de novo. Difficulty: hard to wedge into existing tooling without their code being changed. Another, probably more practical but with a few open questions, would be distinguishing based on how much incoming timestamp diverges from current time. This has the advantage of being all LRS-side.

Of course, LRSs could also just have credentials/scopes for such purposes -- have a credential that always strictly validates profiles on receipt order, have one that defers, etc. Since the profile spec largely doesn't (and probably won't) speak to what an LRS "needs" to do, LRSs could choose the timestamp divergence or credential-based approaches (or mix them, or whatever) -- it'll just be a matter of documenting clearly for users.

Credential-based would be my recommendation for LRSs.

**Comment by fugu13** [comment]
John Costa brings up client-side statement caching -- when a statement is sent to the LRS for the first time could well be many hours after it is generated by the client, which might be disconnected from the internet entirely (such as in an ebook reading scenario).

This makes it difficult to use the timestamp-stored divergence as a basis.

**Comment by fugu13** [comment]
Consensus: timestamp is preferred ordering, never stored.
