### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#44]
For the sake of scope and focus, I propose that we get rid of the communication and validation sections, at least for the initial release. 

Let's just focus on getting a solid json structure for profiles and worry about standardizing transmission and validation later, once people start trying to transmit and validate statements against them.

Maybe we can move that information to a wiki or slack or something for now.

**Comment by aaronesilvers** [comment]
This is a more general proposal and thus belongs on the mailing list, not
GitHub. That said, I'll address this directly.

Anyone is free to focus on the parts of this spec they want to, and if you
want to focus on the construct of a profile, that's helpful.

This spec will be incomplete at best and unusable at worst without
addressing communications and validation, which is why they're in-scope to
begin with. We have use cases to support their merit, so… I'm closing this
issue.

**Comment by garemoko** [comment]
I guess we can always revisit this if we get to the point of having a complete profile spec but the profile server elements aren't complete and are holding up release.

This spec definitely wouldn't be unusable without those elements. I'd use it. 

I'm curious, what are the use cases for a standardized way of hosting profiles and validating statements against a profile server?

**Comment by aaronesilvers** [comment]
@garemoko it's not directly referenced in the spec so you may have missed
it, but use cases can be found in the orientation doc.
https://docs.google.com/document/d/18I-5_4OIOr9ppGxGQKjkvtbQppbl8lMYfrPPMwJszO0

All pertinent files for the effort, including meeting minutes and any
recordings, are here:
http://datainteroperability.org/research-activity-xapi-data-interoperability/xapi-profiles/

**Comment by garemoko** [comment]
Thanks, but which of those use cases requires a standardized way of hosting profiles and validating statements against a profile server? I'm not seeing it.
