### ISSUE TITLE
Concept inScheme Type Clarity

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#63]
In the Concepts table, the element "inScheme" says "the current profile document", can we be more descriptive on what this means?  It seems more accurate that document is Concept (unless I'm misunderstanding the purpose of inScheme)

**Comment by fugu13** [comment]
The current profile document is correct. This relates the concept to the current version of the document. I'm considering changing the term document since it is only used in two places -- it refers to the specific fixation of a given profile version, which is precise and appropriate, but we also use the word document in document resources, so there's potential for confusion.
